version: '3.8'

services:
  movimentai:
    build: .
    image: movimentai:latest
    container_name: movimentai_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: gunicorn --bind 0.0.0.0:8000 app:app